### ISSUE TITLE
Page layout breakout on some MFD (layout shifts up)

### ISSUE THREAD

**Issue by dga711** [dga711/msfs-webui-devkit#1]
On some MFDthe debug panel will somehow break the page layout and the whole page shifts up by a few pixels.
Guess its caused by some weird flex layout the MFDs are based on.

**Comment by Kronzky** [comment]
I've noticed this when the canvas extends beyond the visible frame, i.e. the height of the canvas is 100%, but the top is not at 0. In that situation the console would push down the canvas even further, and its own dialog would end up higher.
I wasn't able to fix it via CSS (I didn't try too hard though), but once I made the canvas a bit shorter (so all would fit into the display) the problem went away.

**Comment by dga711** [comment]
After hours I found out, that it is the scrollIntoView() call on new log element nodes.
This "scrolls" the whole page for some unknown reason. But yeah.

**Comment by dga711** [comment]
Closed via 92179a403e6473cafda7ab3030642a959900636c
