### ISSUE TITLE
@ xml files needed to build package are missing

### ISSUE THREAD

**Issue by 2xlbu4u** [dga711/msfs-webui-devkit#17]
There are 2 xml files needed to create layout.json and manifest.json when building html_ui packages using the in-game debug tools 

They are the project XML at the root of the package sources and the Package XML located in the PackageDefinitions folder.

Please include these 2 XML files so that I can build my own html_ui gauges

Thanks

**Comment by dga711** [comment]
Why would devkit need to provide project xmls for YOUR mod? I don't get it

**Comment by 2xlbu4u** [comment]
I initially didn't see your python code to generate the 2 json files. That makes the need for the XML files obsolete now so thank you for that. It solved my issue.

**Comment by dga711** [comment]
Ok cool. Enjoy!
