### ISSUE TITLE
Request for info: eventListeners/click handlers

### ISSUE THREAD

**Issue by mjkkirschner** [dga711/msfs-webui-devkit#18]
This isn't really an issue with this tool, which btw takes experimenting with the in game panels from a timewasting headache to a pleasant experience.

I'm curious why the display windows need to be moved to new popped out 2d window to become interactive?
Is there a flag somewhere that controls if a particular glasscockpit instrument is capable of listening to event handlers like `click`? while still embedded in the cockpit.

I also noticed that if I add my own buttons to the MFD nested inside the existing divs, even when popped out - something seems to be suppressing the click events. I don't think thats the fault of the debug UI, just an observation, and curious if thats documented somewhere.

**Comment by dga711** [comment]
I didnt really dig into yet, but I guess there is something that can be set to enable the events like on the touch garmins.
By default they non interactive glass instruments dont receive any events without popping them out.

**Comment by dga711** [comment]
My judgement is, that it is the instrument that would have to enable touch or be interactive.
As I mentioned there should be ways to do it. Some instruments set a IsInteractive property to true. 
Maybe you can look into that. 

Will close the issue as I won't do it via devkit. Thanks for your feedback though!
