### ISSUE TITLE
[REQUEST] Show output of init()

### ISSUE THREAD

**Issue by MrMinimal** [dga711/msfs-webui-devkit#19]
First off: Amazing project, using this has been a blast when developing for FBW's A320!

I had an issue today, where my code wasn't executed after a certain line because of a typo.
There was no error shown as it occured in an [init() function](https://github.com/flybywiresim/a32nx/blob/2665e17d24ac35a2b72bdc005ef1d9df087d6ef9/A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_COND.js#L18).

Is there a way these log can be intercepted earlier to also print these errors?

**Comment by dga711** [comment]
I think it depends on where you initialize devkit.
The default example does it in NavSystem connectedCallback which is later than init()

So you could just try initializing devkit earlier.

**Comment by dga711** [comment]
@MrMinimal I did some things via commit 503aa77

Could you please get the changes and test them...

You would have to to the following change
- Remove the init/include code you have somewhere (Navsystem?)
- Add this to VCockpit.html or the html of the instrument of your choice (must be AFTER common.js)
`<script type="text/javascript" src="/JS/debug.js"></script>`

What this change should do
- Get rid of overriding common.js
- The console binding is now initialized very early and should give you all output and errors in the early phase
- Flag to deactivate inspector functionality

**Comment by dga711** [comment]
[WebUI-DevKit_0.9.0-pre1.zip](https://github.com/dga711/msfs-webui-devkit/files/5652069/WebUI-DevKit_0.9.0-pre1.zip)
@MrMinimal bundled it up
