### ISSUE TITLE
Make the window dragable: DragDropHandler not working

### ISSUE THREAD

**Issue by Smirow** [dga711/msfs-webui-devkit#2]
Asobo's `DragDropHandler` seems not to be working. This line is useless:
`this.dragDropHandler = new DragDropHandler(this.m_debugPanel);`

I'll work on a native implementation.

**Comment by dga711** [comment]
Well. The DragDropHandler works when you activate the Console on the web stuff in the menus or UI.

It just doesn't work on the MFDs. Imo it is because the instrument windows don't support full mouse events. Looks like it only takes clicks.

**Comment by Smirow** [comment]
PR  #3

**Comment by dga711** [comment]
Tested it. Works. Looks good.
Thank you for the contribution. Will add credits to the readme soon
