### ISSUE TITLE
Issue with last MSFS update 1.11.6

### ISSUE THREAD

**Issue by pimarc** [dga711/msfs-webui-devkit#20]
Hi
The devkit is not compatible with the last update 1.11.6.0.  It freezes the ingame VFR map and produces errors when used with GPS maps.
This seems to be related to Vec2 class definition (but probably there are some other issues).
For example this one in html_UI/JS/avionics.js line 635:66:
this.rectIntersections[0].SqrDistance is undefined.

**Comment by dga711** [comment]
I'll take a look. Thank you.

In the past I had to ignore a few paths from the cachebusting to not break the game. Maybe some more has to be added.

**Comment by dga711** [comment]
@pimarc are you on the latest version?

I can't reproduce the problems you describe.

**Comment by dga711** [comment]
Ok. I see the problem now. Sorry. Could be their updates to common.js
Will look into fixing it real quick.

**Comment by pimarc** [comment]
Yes exactly
I have one question?
This common.js code comes from where ?
It seems that there are some hidden javascript files I cannot reach: all the html_ui/JS files.
Do you know if these source files are available and where?

Thanks for your reactivity

**Comment by dga711** [comment]
Should be fixed now. Will release a package in a few minutes.

Common.js is in the base files which are not reachable in Store install by normal means.
Since they changed something in patch 1.8.3 I had to start overriding common.js. Which sucks a little bit, but didn't see another way for now.
This makes it so when they change something in there on update, i have to update it with this mod too.

**Comment by pimarc** [comment]
Ok
In any case thanks very much for this tool.
I'm providing a popular mod of the gns530 GPS and without your tool, it was impossible to do.
I will check your update and come back to you if I see any other related issues.

For now I have also this issue probably coming from this common.js change:

In file SvGRoadNetworkElements.js line 466:
if (this.canvasClipping.segmentVsRect(n1, n2, s1, s2)) {

I have an undefined reported in the log as this:
html_UI/JS/avionics.js line 635:66:
this.rectIntersections[0].SqrDistance is undefined.

**Comment by pimarc** [comment]
Tested your update. Everything goes well.

Thanks again for your reactivity.

**Comment by dga711** [comment]
Great!
Thanks for you feedback. Because I didn't notice it until your issue ;)
