### ISSUE TITLE
G1000 reload

### ISSUE THREAD

**Issue by hugo-cardoso** [dga711/msfs-webui-devkit#22]
Hello Guys! I'm trying to update the content of the G1000 but the hotkeys don't work and I can't click the buttons because the screen is not touch. How to proceed?

**Comment by erictg** [comment]
I'm having this issue as well, im going to fork it and try to link them to key bindings.

**Comment by erictg** [comment]
@hugo-cardoso never mind on that. Pop out the window with right alt + click. I am still having the problem of the hot keys not working.

**Comment by dga711** [comment]
With non touch displays you have to do it as @erictg described. The instructions are also in the readme.

I will see what I can find out about the Hotkeys.
