### ISSUE TITLE
Devkit causes crashes when hotreloading

### ISSUE THREAD

**Issue by Username23-23** [dga711/msfs-webui-devkit#24]
Hello, 
I've been having issues with the devkit when I'm using it with the A32NX mod. 
When I hit the reload button, the sim freezes and crashes to desktop. In a few cases, it actually caused my computer to shut down.
I'll try to see if I can reproduce this with other aircraft.
edit: it seems to be the case with almost all aircraft. If it helps, I haven't been getting these CTDs when I'm not using the devkit.

**Comment by dga711** [comment]
Right now I don't really see anything I could look for here. Didn't get any other reports of that happening

**Comment by Username23-23** [comment]
Yeah, honestly it seems like more of an MSFS issue, so I’m closing.
