### ISSUE TITLE
Add panel to access SimVar/SimPlane values

### ISSUE THREAD

**Issue by dga711** [dga711/msfs-webui-devkit#5]
It could be very useful to see SimVar/SimPlane values ingame during runtime.

**Comment by OzWookiee** [comment]
Use the example SimVarWatcher app from the SDK Samples.

**Comment by dga711** [comment]
Yeah, some implementation like that would be quite nice.
Although, as good as it sounded to me at first, I am now debating if it would really be a useful feature to have in game. Considering we have the watcher app.

**Comment by OzWookiee** [comment]
Yea that's what I mean, don't really need it wil the watcher app being there.

**Comment by dga711** [comment]
I don't see a reason to do it anymore, too. Was just a brainfart. Closed. Thanks for your input.
